### ISSUE TITLE
doctype 5 deprecated

### ISSUE THREAD

**Issue by kevindashgit** [rhysr/angular-express-seed#2]
OOB I get this error:

```
Express
500 Error: /Users/kevindashgit/angular-seed/angular-express-seed/views/layout.jade:1 > 1| doctype 5 2| html(ng-app="myapp") 3| head 4| link(rel='stylesheet', href='/stylesheets/style.css') `doctype 5` is deprecated, you must now use `doctype html`
> 1| doctype 5
2| html(ng-app="myapp")
3| head
4| link(rel='stylesheet', href='/stylesheets/style.css')
`doctype 5` is deprecated, you must now use `doctype html`
at Object.Lexer.doctype (/Users/kevindashgit/angular-seed/angular-express-seed/node_modules/jade/lib/lexer.js:256:13)
at Object.Lexer.next (/Users/kevindashgit/angular-seed/angular-express-seed/node_modules/jade/lib/lexer.js:916:15)
at Object.Lexer.lookahead (/Users/kevindashgit/angular-seed/angular-express-seed/node_modules/jade/lib/lexer.js:113:46)
at Parser.lookahead (/Users/kevindashgit/angular-seed/angular-express-seed/node_modules/jade/lib/parser.js:102:23)
at Parser.peek (/Users/kevindashgit/angular-seed/angular-express-seed/node_modules/jade/lib/parser.js:79:17)
at Parser.parse (/Users/kevindashgit/angular-seed/angular-express-seed/node_modules/jade/lib/parser.js:117:26)
at Parser.parse (/Users/kevindashgit/angular-seed/angular-express-seed/node_modules/jade/lib/parser.js:131:24)
at parse (/Users/kevindashgit/angular-seed/angular-express-seed/node_modules/jade/lib/index.js:104:21)
at Object.exports.compile (/Users/kevindashgit/angular-seed/angular-express-seed/node_modules/jade/lib/index.js:205:16)
at handleTemplateCache (/Users/kevindashgit/angular-seed/angular-express-seed/node_modules/jade/lib/index.js:174:25)
```

The fix is to do as the error suggests.

Also a `.gitignore` with `node_modules/` would be a nice value add.

**Comment by rhysr** [comment]
Thanks for letting me know.
I've also pinned the jade version so this won't happen again.
Do you mind if I ask why you chose to fork this repo?
I don't mind at all, but I've not touched it in nearly 4 years.
There must be better repos out there! :)

**Comment by kevindashgit** [comment]
Was looking for a very simple boilerplate that included express + jade + angular 1.x - this fit the bill for me.
